version: '1'
services:
  bot:
    container_name: telegram-bot
    build:
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - membase

  membase:
    image: mongo
    container_name: membase
    hostname: membase
    ports:
      - 27017:27017